ALTER TABLE companys ADD COLUMN industry VARCHAR(100) DEFAULT '';
ALTER TABLE companys ADD COLUMN phone VARCHAR(50) DEFAULT '';
ALTER TABLE companys ADD COLUMN brand_name VARCHAR(100) DEFAULT '';
ALTER TABLE companys ADD COLUMN brand_positioning VARCHAR(255) DEFAULT '';
ALTER TABLE companys ADD COLUMN region VARCHAR(255) DEFAULT '';
ALTER TABLE companys ADD COLUMN address_detail TEXT DEFAULT '';
